### ISSUE TITLE
Can't upload multiple files

### ISSUE THREAD

**Issue by hoanguel** [bkstar123/laravel-uploader#2]
Hi,

Thank you for your contribution. I am trying to make use of this package for multiple files upload in Laravel 8 but it is without success. In my view, I have this line here:

`<input class="form-control" type="file" name="template_files[]" id="template_files" multiple>`

and I loaded the following assets:

```
<script src="/vendor/fileupload/js/fileinput/fileinput.min.js"></script>
<link href="/vendor/fileupload/css/fileinput/fileinput.min.css" rel="stylesheet">
```

and the script:

```
<script type="text/javascript">
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $("#template_files").fileinput(
            {
                uploadUrl: '/template/store',
                data-browse-on-zone-click: true,
                dropZoneEnabled: true,
                maxFileCount: 5,
                maxFileSize: 10420, //in KBs
                allowedFileExtensions: ['jpg', 'png', 'pdf', 'html', 'htm', 'json'],
                previewFileType:'any',
                showUpload: false
            }
        ).on("filebatchselected", function(event, files) {
            $("#template_files").fileinput("upload");  
        });
    });    
</script>
```

In my controller, I have this:

```
if ($path = $this->fileupload->handle($request, 'template_files')) {
            // Persist $path data to database
            return json_encode([]);
}

return json_encode([
            'error' => $this->fileupload->uploadError
]);
```

But either I will have only one file uploaded when input name set to this `name="template_files"`. If change it to `name="template_files[]"` for multiple files upload I will have this error:

`Argument 1 passed to Bkstar123\LaravelUploader\Services\FileUpload::uploadValidate() must be an instance of Illuminate\Http\UploadedFile, array given, called in /var/www/html/my-project/vendor/bkstar123/laravel-uploader/src/Abstracts/FileUploadAbstract.php on line 52 `

Could you give any advice, please? Thank you!

**Comment by bkstar123** [comment]
Hi @hoanguel

Thank you very much for using my package. I am really sorry to hear that you are facing an issue when implementing it in your project.

The package actually intends to process a single file uploading but not multiple files uploading at the backend server. It seems awkward at first, but the plan is to use it with an Ajax file uploading client such as the "fileinput" JQuery plugin. The JS client can be configured for multiple file uploading, in that case the JS client will send multiple files to the backend server via separate AJAX post requests. Then, the server process them one by one in an asynchronous way.  The client side just see that multiple files can be selected and sent to the server at once.

So do not use ```name="template_files[]"```,  just use ```name="template_files"``` & configure "fileinput" JQuery plugin to allow select multiple files & send them to the backend server in a batch. I can do multiple files uploading in this way for my projects.

**Note:**
Do not forget to add the attribute ```multiple="true""``` to the HTML file input tag, for example:
```html 
<input class="form-control" type="file" name="template_files" id="template_files" multiple>
```

In my opinion, it is not good to select multiple files and send all via a single request to the server (the size of POST data may be too large, right?). We should send multiple files to the backend server on different requests (one request for one file) in an asynchronous way .

Also, I wrote a simple AJAX file upload client in https://github.com/bkstar123/jquery-ajax-uploader, you can use it. 

If you need any other help or have any concern, feel free to let me know

Thank you again for your feedback

**Comment by bkstar123** [comment]
I closed the issue as it is working as design. You just need to enable sending multiple files from the client side via AJAX, then you will be able to upload multiple files to the server. 

In your situation, you need to use the following HTML input tag
```html
<input class="form-control" type="file" name="template_files" id="template_files" multiple>
```

The JS code is OK, no need to change.

If you still face any issue, feel free to re-open the issue
